# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa8624129c9feea2ac81dd6ed9686d8f9144279d7c7829e2bab45487ddad1570e732e4f9239e5ecd9d540a5c7f560aa0a65e9e6ec2a10fdd49621882bb84426a

test:
  secret_key_base: 234519167c5d059ea338a565d0c1e856c1ff286b37cdefd8aecf0b933724fa24b4b8ef68fe0001b009793371c9d37fdac7439375ab6ef98f53d70266a2a90d6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
